language: csharp
solution: src/Askaiser.Mobile.Pillar.sln
install:
  - nuget restore src/Askaiser.Mobile.Pillar.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/Askaiser.Mobile.Pillar.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./tests/Askaiser.Mobile.Pillar.Tests/bin/Release/Askaiser.Mobile.Pillar.Tests.dll